repos:
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
    language_version: python3.11
- repo: "https://github.com/PyCQA/isort"
  rev: "5.12.0"
  hooks:
    - id: "isort"
      args: ["--profile", "black"]
      name: "Format code (isort)"
      language_version: "python3.11"
      types: ["python"]
- repo: "https://github.com/myint/autoflake"
  rev: v2.0.1
  hooks:
    - id: autoflake
      args: ["--in-place", "--remove-all-unused-imports", "--remove-unused-variable"]
