version: '3.6'
services:

  zookeeper:
    restart: always
    image: bitnami/zookeeper:3.7
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./data/zookeeper:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:3.3
    volumes:
      - ./data/kafka:/bitnami/kafka
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  kafdrop:
    restart: always
    image: obsidiandynamics/kafdrop
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
    depends_on:
      - kafka
    ports:
      - 9000:9000

  tron:
    image: java-tron
    entrypoint: ["./bin/docker-entrypoint.sh", "-c", "/java-tron/config/test_net_config.conf", "--es", "--log-config", "/java-tron/config/logback.xml"]
    volumes:
      - /Users/pomeschenkoanton/projects/tronql/data/testnet/node:/java-tron/output-directory
      - /Users/pomeschenkoanton/projects/tronql/data/testnet/logs:/java-tron/logs
    depends_on:
      - kafka
    ports:
      - 8090:8090
      - 18888:18888
      - 50051:50051
    container_name: java-tron
