"""add_archway

Revision ID: eda78559c9a2
Revises: 836424188de1
Create Date: 2023-04-17 23:57:13.465649

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eda78559c9a2"
down_revision = "836424188de1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "networks", sa.Column("header_in_domain", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE networks SET header_in_domain = true;")

    meta = sa.MetaData()
    meta.reflect(bind=op.get_bind(), only=("networks",))
    networks = sa.Table("networks", meta)

    op.bulk_insert(
        networks,
        [
            {
                "slug": "archway-constantine-2",
                "title": "Archway constantine",
                "domain": "constantine-2.archway.tronql.com",
                "header_in_domain": False,
            },
        ],
    )

    op.alter_column("networks", "header_in_domain", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("networks", "header_in_domain")
    op.execute("DELETE FROM networks WHERE slug = 'archway-constantine-2';")
    # ### end Alembic commands ###
