"""add_networks_table

Revision ID: 836424188de1
Revises:
Create Date: 2023-04-14 19:15:58.191185

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "836424188de1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    networks = op.create_table(
        "networks",
        sa.Column("slug", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("domain", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("slug"),
    )

    op.bulk_insert(
        networks,
        [
            {
                "slug": "tron-mainnet",
                "title": "Tron mainnet",
                "domain": "mainnet.tron.tronql.com",
            },
            {
                "slug": "tron-nile",
                "title": "Tron test network nile",
                "domain": "nile.tron.tronql.com",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("networks")
    # ### end Alembic commands ###
