"""add_plan_fields

Revision ID: 644460d08001
Revises: b4db0f345a09
Create Date: 2023-03-21 22:54:02.546145

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "644460d08001"
down_revision = "b4db0f345a09"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects_plans", sa.Column("title", sa.Text(), nullable=True))
    op.add_column("projects_plans", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "projects_plans", sa.Column("visibility", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "projects_plans",
        sa.Column("price", sa.Numeric(precision=60, scale=18), nullable=True),
    )
    op.add_column(
        "projects_plans", sa.Column("currency", sa.String(length=20), nullable=True)
    )

    op.execute(
        """
        UPDATE projects_plans SET title = 'Basic plan', description = 'Just basic plan', visibility = 'public', price = NULL, currency = NULL WHERE slug = 'basic';
        UPDATE projects_plans SET title = 'Liquidathor plan', description = 'Only for Liquidathor project', visibility = 'private', price = NULL, currency = NULL WHERE slug = 'liquidathor';
    """
    )

    op.alter_column("projects_plans", "visibility", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects_plans", "currency")
    op.drop_column("projects_plans", "price")
    op.drop_column("projects_plans", "visibility")
    op.drop_column("projects_plans", "description")
    op.drop_column("projects_plans", "title")
    # ### end Alembic commands ###
