"""add_plans

Revision ID: aed27346a252
Revises: c8995f3d5ef3
Create Date: 2023-05-27 23:23:01.034604

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aed27346a252"
down_revision = "c8995f3d5ef3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    meta = sa.MetaData()
    meta.reflect(bind=op.get_bind(), only=("projects_plans",))

    plans = sa.Table("projects_plans", meta)

    op.bulk_insert(
        plans,
        [
            {
                "slug": "start",
                "requests_per_month": 5_000_000,
                "rate_limit": 50,
                "rate_period": 1,
                "visibility": "public",
                "title": "Start for Startup",
                "description": "Common plan for startups that need low number of api calls",
                "price": 10,
                "currency": "USDT",
            },
            {
                "slug": "advanced",
                "requests_per_month": 20_000_000,
                "rate_limit": 75,
                "rate_period": 1,
                "visibility": "public",
                "title": "Advanced plan",
                "description": "Plan that allows you to execute a lot of calls. Suitable for middle startups",
                "price": 20,
                "currency": "USDT",
            },
            {
                "slug": "vip",
                "requests_per_month": 100_000_000,
                "rate_limit": 100,
                "rate_period": 1,
                "visibility": "public",
                "title": "Pro plan",
                "description": "Wow 100M requests. You probably need a lot of data. Contantly monitoring blockchain. For big projects.",
                "price": 80,
                "currency": "USDT",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM projects_plans WHERE slug = 'start';")
    op.execute("DELETE FROM projects_plans WHERE slug = 'advanced';")
    op.execute("DELETE FROM projects_plans WHERE slug = 'vip';")
    # ### end Alembic commands ###
