"""update_basic_plan

Revision ID: f3426fc5ced0
Revises: 644460d08001
Create Date: 2023-03-28 18:31:41.270749

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "f3426fc5ced0"
down_revision = "644460d08001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE projects_plans SET requests_per_month = 5000000 WHERE slug = 'basic';"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE projects_plans SET requests_per_month = 500000 WHERE slug = 'basic';"
    )
    # ### end Alembic commands ###
